import { User, Company } from '../types';

export const MASTER_COMPANIES: Company[] = [
  { id: 'comp_hdi_world', name: 'HDI WORLD', code: 'HDIW', isActive: true },
  { id: 'comp_hillcroft', name: 'Hillcroft Properties', code: 'HILL', isActive: true },
  { id: 'comp_capital_growth', name: 'Capital Growth Properties', code: 'CGP', isActive: true },
  { id: 'comp_erminland', name: 'Erminland Properties', code: 'ERM', isActive: true },
  { id: 'comp_stanford', name: 'Stanford', code: 'STAN', isActive: true },
  { id: 'comp_adventures', name: 'Adventures', code: 'ADV', isActive: true },
];

export const MASTER_EMPLOYEES: User[] = [
  // ── EXECUTIVE (CEO) ────────────────────────────────────────────────────────
  {
    id: 'usr_ceo_brandon',
    employeeNumber: 'CEO-001',
    firstName: 'Brandon',
    lastName: 'Chia',
    name: 'Brandon Chia',
    email: 'brandon.chia@hdiadventures.com',
    username: 'brandon.chia',
    password: 'password',
    role: 'president',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_exec',
    departmentName: 'Executive Office',
    position: 'Chief Executive Officer',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },

  // ── DEFAULT SYSTEM ADMIN ───────────────────────────────────────────────────
  {
    id: 'usr_default_admin',
    employeeNumber: 'ADMIN-001',
    firstName: 'System',
    lastName: 'Administrator',
    name: 'System Administrator',
    email: 'Admin.Systemad@hdiadventures.com',
    username: 'Admin.Systemad',
    password: 'ADMIN',
    role: 'system_admin',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_adm',
    departmentName: 'Admin',
    position: 'System Administrator',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
    requiresPasswordChange: true,
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
  },

  // ── SHEET 1: HDI WORLD (12 Records) ───────────────────────────────────────
  {
    id: 'usr_e1572',
    employeeNumber: 'E1572',
    firstName: 'Lucil',
    middleName: 'Albino',
    lastName: 'Osorio',
    name: 'Lucil Osorio',
    email: 'lucil.osorio@hdiworld.com',
    username: 'lucil.osorio',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_ops_hdiw',
    departmentName: 'Operations',
    position: 'Junior Project Leader-Operations',
    immediateSuperiorId: 'usr_r132',
    immediateSuperiorName: 'Ma. Emily Floresca',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1653',
    employeeNumber: 'E1653',
    firstName: 'Benjie',
    middleName: 'Surot',
    lastName: 'De Guzman',
    name: 'Benjie De Guzman',
    email: 'benjie.deguzman@hdiworld.com',
    username: 'benjie.deguzman',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_wh_hdiw',
    departmentName: 'Warehouse',
    position: 'Support Member-Driver',
    immediateSuperiorId: 'usr_e1572',
    immediateSuperiorName: 'Lucil Osorio',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_r630',
    employeeNumber: 'R630',
    firstName: 'Lilibeth',
    middleName: 'Ortega',
    lastName: 'De la Cruz',
    name: 'Lilibeth De la Cruz',
    email: 'lilibeth.delacruz@hdiworld.com',
    username: 'lilibeth.delacruz',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_cebu_hdiw',
    departmentName: 'Cebu Branch',
    position: 'Junior Project Leader-Business Development',
    immediateSuperiorId: 'usr_r132',
    immediateSuperiorName: 'Ma. Emily Floresca',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1788',
    employeeNumber: 'E1788',
    firstName: 'Leonardo',
    middleName: 'Big-Asan',
    lastName: 'Mercado',
    name: 'Leonardo Mercado',
    email: 'leonardo.mercado@hdiworld.com',
    username: 'leonardo.mercado',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_ops_hdiw',
    departmentName: 'Operations',
    position: 'Support Member-Delivery Rider/Messenger',
    immediateSuperiorId: 'usr_e1572',
    immediateSuperiorName: 'Lucil Osorio',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1396',
    employeeNumber: 'E1396',
    firstName: 'Junielyn',
    middleName: 'Bardenas',
    lastName: 'Nuique',
    name: 'Junielyn Nuique',
    email: 'junielyn.nuique@hdiworld.com',
    username: 'junielyn.nuique',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_cebu_hdiw',
    departmentName: 'Cebu Branch',
    position: 'Junior Project Leader-Business Development',
    immediateSuperiorId: 'usr_r132',
    immediateSuperiorName: 'Ma. Emily Floresca',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1494',
    employeeNumber: 'E1494',
    firstName: 'Arnold',
    middleName: 'Alcantara',
    lastName: 'Orijuela',
    name: 'Arnold Orijuela',
    email: 'arnold.orijuela@hdiworld.com',
    username: 'arnold.orijuela',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_wh_hdiw',
    departmentName: 'Warehouse',
    position: 'Support Member-Warehouseman/Driver',
    immediateSuperiorId: 'usr_e1572',
    immediateSuperiorName: 'Lucil Osorio',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1771',
    employeeNumber: 'E1771',
    firstName: 'Gennelyn',
    middleName: 'Isip',
    lastName: 'Raper',
    name: 'Gennelyn Raper',
    email: 'gennelyn.raper@hdiworld.com',
    username: 'gennelyn.raper',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_ops_hdiw',
    departmentName: 'Operations',
    position: 'Support Member-Administrative',
    immediateSuperiorId: 'usr_e1572',
    immediateSuperiorName: 'Lucil Osorio',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1795',
    employeeNumber: 'E1795',
    firstName: 'Jainy',
    middleName: 'Laciste',
    lastName: 'Mostairo',
    name: 'Jainy Mostairo',
    email: 'jainy.mostairo@hdiworld.com',
    username: 'jainy.mostairo',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_acctg_ga_hdiw',
    departmentName: 'Acctg and GA',
    position: 'Team Member - Finance and Accounting',
    immediateSuperiorId: 'usr_e1714',
    immediateSuperiorName: 'Dana Miran',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1802',
    employeeNumber: 'E1802',
    firstName: 'Rubelle',
    middleName: 'Quezon',
    lastName: 'Gersan',
    name: 'Rubelle Gersan',
    email: 'rubelle.gersan@hdiworld.com',
    username: 'rubelle.gersan',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_cebu_hdiw',
    departmentName: 'Cebu Branch',
    position: 'Support Member-Branch Operations',
    immediateSuperiorId: 'usr_e1396',
    immediateSuperiorName: 'Junielyn Nuique',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1803',
    employeeNumber: 'E1803',
    firstName: 'Reynaldo Jr.',
    middleName: 'Enriquez',
    lastName: 'Dizon',
    name: 'Reynaldo Dizon Jr.',
    email: 'reynaldo.dizon@hdiworld.com',
    username: 'reynaldo.dizon',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_branch_ops_hdiw',
    departmentName: 'Branch Operations',
    position: 'Support Member-Branch Operations',
    immediateSuperiorId: 'usr_e1572',
    immediateSuperiorName: 'Lucil Osorio',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1821',
    employeeNumber: 'E1821',
    firstName: 'Ruby',
    middleName: 'Fernandez',
    lastName: 'Madrid',
    name: 'Ruby Madrid',
    email: 'ruby.madrid@hdiworld.com',
    username: 'ruby.madrid',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_ops_hdiw',
    departmentName: 'Operations',
    position: 'Senior Team Leader-Community Marketing',
    immediateSuperiorId: 'usr_r132',
    immediateSuperiorName: 'Ma. Emily Floresca',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_1826',
    employeeNumber: '1826',
    firstName: 'Emily',
    middleName: 'Namilit',
    lastName: 'Balaga',
    name: 'Emily Balaga',
    email: 'emily.balaga@hdiworld.com',
    username: 'emily.balaga',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hdi_world',
    companyName: 'HDI WORLD',
    departmentId: 'dept_davao_hdiw',
    departmentName: 'Davao branch',
    position: 'Junior Project Leader - Sales Maverick',
    immediateSuperiorId: 'usr_e1396',
    immediateSuperiorName: 'Junielyn Nuique',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },

  // ── SHEET 2: HILLCROFT PROPERTIES (3 Records) ──────────────────────────────
  {
    id: 'usr_e1151',
    employeeNumber: 'E1151',
    firstName: 'Mark Anthony',
    middleName: 'Enriquez',
    lastName: 'Eliseo',
    name: 'Mark Anthony Eliseo',
    email: 'markanthony.eliseo@hillcroft.com',
    username: 'markanthony.eliseo',
    password: 'password',
    role: 'employee',
    companyId: 'comp_hillcroft',
    companyName: 'Hillcroft Properties',
    departmentId: 'dept_ga_hill',
    departmentName: 'General Affairs',
    position: 'Support Member-Driver/Messenger',
    immediateSuperiorId: 'usr_r132',
    immediateSuperiorName: 'Ma. Emily Floresca',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_r132',
    employeeNumber: 'R132',
    firstName: 'Ma. Emily',
    middleName: 'Peralta',
    lastName: 'Floresca',
    name: 'Ma. Emily Floresca',
    email: 'emily.floresca@hillcroft.com',
    username: 'emily.floresca',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_hillcroft',
    companyName: 'Hillcroft Properties',
    departmentId: 'dept_ga_hill',
    departmentName: 'General Affairs',
    position: 'Team Leader-General Affairs',
    immediateSuperiorId: 'usr_ceo_brandon',
    immediateSuperiorName: 'Brandon Chia',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1806',
    employeeNumber: 'E1806',
    firstName: 'Mary Anne',
    middleName: 'Udtujan',
    lastName: 'Murphy',
    name: 'Mary Anne Murphy',
    email: 'maryanne.murphy@hillcroft.com',
    username: 'maryanne.murphy',
    password: 'password',
    role: 'dept_head',
    companyId: 'comp_hillcroft',
    companyName: 'Hillcroft Properties',
    departmentId: 'dept_fa_hill',
    departmentName: 'Finance and Accounting',
    position: 'Senior Team Leader-Finance and Accounting',
    immediateSuperiorId: 'usr_ceo_brandon',
    immediateSuperiorName: 'Brandon Chia',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },

  // ── SHEET 3: CAPITAL GROWTH PROPERTIES (8 Records) ─────────────────────────
  {
    id: 'usr_e984',
    employeeNumber: 'E984',
    firstName: 'Judycel',
    middleName: 'Mateo',
    lastName: 'Delos Reyes',
    name: 'Judycel Delos Reyes',
    email: 'judycel.delosreyes@capitalgrowth.com',
    username: 'judycel.delosreyes',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_capital_growth',
    companyName: 'Capital Growth Properties',
    departmentId: 'dept_cb_cgp',
    departmentName: 'Compensation & Benefits',
    position: 'Team Leader-Compensation and Benefits',
    immediateSuperiorId: 'usr_e1806',
    immediateSuperiorName: 'Mary Anne Murphy',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1538',
    employeeNumber: 'E1538',
    firstName: 'Pamela Maureen',
    middleName: 'Soriano',
    lastName: 'Fernando',
    name: 'Pamela Maureen Fernando',
    email: 'pamela.fernando@capitalgrowth.com',
    username: 'pamela.fernando',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_capital_growth',
    companyName: 'Capital Growth Properties',
    departmentId: 'dept_chair_cgp',
    departmentName: 'Office of the Chairman',
    position: 'Senior Team Leader-Country Coordinator',
    immediateSuperiorId: 'usr_ceo_brandon',
    immediateSuperiorName: 'Brandon Chia',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e995',
    employeeNumber: 'E995',
    firstName: 'Eugene Paul',
    middleName: 'Valdez',
    lastName: 'Parel',
    name: 'Eugene Paul Parel',
    email: 'eugenepaul.parel@capitalgrowth.com',
    username: 'eugenepaul.parel',
    password: 'password',
    role: 'employee',
    companyId: 'comp_capital_growth',
    companyName: 'Capital Growth Properties',
    departmentId: 'dept_ga_cgp',
    departmentName: 'General Affairs',
    position: 'Support Member-Driver/Messenger',
    immediateSuperiorId: 'usr_r132',
    immediateSuperiorName: 'Ma. Emily Floresca',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1503',
    employeeNumber: 'E1503',
    firstName: 'Gerard',
    middleName: 'Valeros',
    lastName: 'Marquez',
    name: 'Gerard Marquez',
    email: 'gerard.marquez@capitalgrowth.com',
    username: 'gerard.marquez',
    password: 'password',
    role: 'employee',
    companyId: 'comp_capital_growth',
    companyName: 'Capital Growth Properties',
    departmentId: 'dept_ga_cgp',
    departmentName: 'General Affairs',
    position: 'Support Member-Messenger',
    immediateSuperiorId: 'usr_r132',
    immediateSuperiorName: 'Ma. Emily Floresca',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_er006',
    employeeNumber: 'ER006',
    firstName: 'Zona Rocelle',
    middleName: '',
    lastName: 'Merto',
    name: 'Zona Rocelle Merto',
    email: 'zonarocelle.merto@capitalgrowth.com',
    username: 'zonarocelle.merto',
    password: 'password',
    role: 'employee',
    companyId: 'comp_capital_growth',
    companyName: 'Capital Growth Properties',
    departmentId: 'dept_cb_cgp',
    departmentName: 'Compensation & Benefits',
    position: undefined,
    immediateSuperiorId: 'usr_e984',
    immediateSuperiorName: 'Judycel Delos Reyes',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_er007',
    employeeNumber: 'ER007',
    firstName: 'Paula Angila',
    middleName: '',
    lastName: 'Vaflor',
    name: 'Paula Angila Vaflor',
    email: 'paulaangila.vaflor@capitalgrowth.com',
    username: 'paulaangila.vaflor',
    password: 'password',
    role: 'employee',
    companyId: 'comp_capital_growth',
    companyName: 'Capital Growth Properties',
    departmentId: 'dept_cb_cgp',
    departmentName: 'Compensation & Benefits',
    position: undefined,
    immediateSuperiorId: 'usr_e984',
    immediateSuperiorName: 'Judycel Delos Reyes',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1823',
    employeeNumber: 'E1823',
    firstName: 'Gereca',
    middleName: 'Nabua',
    lastName: 'Lim',
    name: 'Gereca Lim',
    email: 'gereca.lim@capitalgrowth.com',
    username: 'gereca.lim',
    password: 'password',
    role: 'employee',
    companyId: 'comp_capital_growth',
    companyName: 'Capital Growth Properties',
    departmentId: 'dept_fa_cgp',
    departmentName: 'Finance and Accounting',
    position: 'Team Member - Finance and Accounting',
    immediateSuperiorId: 'usr_e1714',
    immediateSuperiorName: 'Dana Miran',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1827',
    employeeNumber: 'E1827',
    firstName: 'Thessalonica',
    middleName: 'Taton',
    lastName: 'Delos Santos',
    name: 'Thessalonica Delos Santos',
    email: 'thessalonica.delossantos@capitalgrowth.com',
    username: 'thessalonica.delossantos',
    password: 'password',
    role: 'employee',
    companyId: 'comp_capital_growth',
    companyName: 'Capital Growth Properties',
    departmentId: 'dept_legal_cgp',
    departmentName: 'Legal',
    position: 'Team Member - Paralegal',
    immediateSuperiorId: 'usr_e1813',
    immediateSuperiorName: 'Jemimah Naomi De Los Santos',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },

  // ── SHEET 4: ERMINLAND PROPERTIES (3 Records) ──────────────────────────────
  {
    id: 'usr_e1161',
    employeeNumber: 'E1161',
    firstName: 'Jorge',
    middleName: 'Mora',
    lastName: 'Barraca',
    name: 'Jorge Barraca',
    email: 'jorge.barraca@erminland.com',
    username: 'jorge.barraca',
    password: 'password',
    role: 'employee',
    companyId: 'comp_erminland',
    companyName: 'Erminland Properties',
    departmentId: 'dept_ga_erm',
    departmentName: 'General Affairs',
    position: 'Support Member-Maintenance',
    immediateSuperiorId: 'usr_r132',
    immediateSuperiorName: 'Ma. Emily Floresca',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1714',
    employeeNumber: 'E1714',
    firstName: 'Dana',
    middleName: 'Bernardino',
    lastName: 'Miran',
    name: 'Dana Miran',
    email: 'dana.miran@erminland.com',
    username: 'dana.miran',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_erminland',
    companyName: 'Erminland Properties',
    departmentId: 'dept_fin_erm',
    departmentName: 'Finance',
    position: 'Team Member-Accounting',
    immediateSuperiorId: 'usr_e1806',
    immediateSuperiorName: 'Mary Anne Murphy',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1302',
    employeeNumber: 'E1302',
    firstName: 'Anmer',
    middleName: 'Bantay',
    lastName: 'Carrillo',
    name: 'Anmer Carrillo',
    email: 'anmer.carrillo@erminland.com',
    username: 'anmer.carrillo',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_erminland',
    companyName: 'Erminland Properties',
    departmentId: 'dept_bmc_erm',
    departmentName: 'BMC',
    position: 'Team Leader-Creative Design',
    immediateSuperiorId: 'usr_e1538',
    immediateSuperiorName: 'Pamela Maureen Fernando',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },

  // ── SHEET 5: STANFORD (1 Record) ───────────────────────────────────────────
  {
    id: 'usr_e1401',
    employeeNumber: 'E1401',
    firstName: 'Reziel',
    middleName: 'Estera',
    lastName: 'Rivera',
    name: 'Reziel Rivera',
    email: 'reziel.rivera@stanford.com',
    username: 'reziel.rivera',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_stanford',
    companyName: 'Stanford',
    departmentId: 'dept_ops_stan',
    departmentName: 'Operations',
    position: 'Project Leader-Operations',
    immediateSuperiorId: 'usr_ceo_brandon',
    immediateSuperiorName: 'Brandon Chia',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },

  // ── SHEET 6: ADVENTURES (33 Records) ───────────────────────────────────────
  {
    id: 'usr_e1333',
    employeeNumber: 'E1333',
    firstName: 'Kennedy',
    middleName: 'Lucas',
    lastName: 'Abundo',
    name: 'Kennedy Abundo',
    email: 'kennedy.abundo@hdiadventures.com',
    username: 'kennedy.abundo',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_ops_adv',
    departmentName: 'Operations',
    position: 'Support Member-Compliance',
    immediateSuperiorId: 'usr_e1115',
    immediateSuperiorName: 'Manuel, Jr. Embuido',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1356',
    employeeNumber: 'E1356',
    firstName: 'Marites',
    middleName: 'Estanislao',
    lastName: 'Bacle',
    name: 'Marites Bacle',
    email: 'marites.bacle@hdiadventures.com',
    username: 'marites.bacle',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_sales_adv',
    departmentName: 'Sales',
    position: 'Team Member-Sales',
    immediateSuperiorId: 'usr_e1147',
    immediateSuperiorName: 'Gracia Esguerra',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1114',
    employeeNumber: 'E1114',
    firstName: 'Teoderico',
    middleName: 'Sucgang',
    lastName: 'Bato',
    name: 'Teoderico Bato',
    email: 'teoderico.bato@hdiadventures.com',
    username: 'teoderico.bato',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_ops_adv',
    departmentName: 'Operations',
    position: 'Support Member-Ad and Site Inspector',
    immediateSuperiorId: 'usr_e1115',
    immediateSuperiorName: 'Manuel, Jr. Embuido',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1752',
    employeeNumber: 'E1752',
    firstName: 'Emmanuel',
    middleName: 'Joaquin',
    lastName: 'Buenaventura',
    name: 'Emmanuel Buenaventura',
    email: 'emmanuel.buenaventura@hdiadventures.com',
    username: 'emmanuel.buenaventura',
    password: 'password',
    role: 'dept_head',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_fa_adv',
    departmentName: 'Finance and Accounting',
    position: 'Senior Team Leader-Finance',
    immediateSuperiorId: 'usr_ceo_brandon',
    immediateSuperiorName: 'Brandon Chia',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1191',
    employeeNumber: 'E1191',
    firstName: 'Alvin',
    middleName: 'Garcia',
    lastName: 'Cudyamat',
    name: 'Alvin Cudyamat',
    email: 'alvin.cudyamat@hdiadventures.com',
    username: 'alvin.cudyamat',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_ops_adv',
    departmentName: 'Operations',
    position: 'Junior Project Leader-Installation',
    immediateSuperiorId: 'usr_e1115',
    immediateSuperiorName: 'Manuel, Jr. Embuido',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1402',
    employeeNumber: 'E1402',
    firstName: 'Edward',
    middleName: 'Anaque',
    lastName: 'Gunobgunob',
    name: 'Edward Gunobgunob',
    email: 'edward.gunobgunob@hdiadventures.com',
    username: 'edward.gunobgunob',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_ops_adv',
    departmentName: 'Operations',
    position: 'Junior Project Leader-Electrical',
    immediateSuperiorId: 'usr_e1115',
    immediateSuperiorName: 'Manuel, Jr. Embuido',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1527',
    employeeNumber: 'E1527',
    firstName: 'Maria Elena',
    middleName: 'Nazareno',
    lastName: 'Pellazo',
    name: 'Maria Elena Pellazo',
    email: 'mariaelena.pellazo@hdiadventures.com',
    username: 'mariaelena.pellazo',
    password: 'password',
    role: 'pod',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_pod_adv',
    departmentName: 'Peoples Ops',
    position: 'Team Leader-People Operations',
    immediateSuperiorId: 'usr_ceo_brandon',
    immediateSuperiorName: 'Brandon Chia',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1566',
    employeeNumber: 'E1566',
    firstName: 'Mallory Tizehl',
    middleName: 'Catapat',
    lastName: 'Narciso',
    name: 'Mallory Tizehl Narciso',
    email: 'mallorytizehl.narciso@hdiadventures.com',
    username: 'mallorytizehl.narciso',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_fa_adv',
    departmentName: 'Finance and Accounting',
    position: 'Junior Project Leader-Billing and Collection',
    immediateSuperiorId: 'usr_e1806',
    immediateSuperiorName: 'Mary Anne Murphy',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_bb225',
    employeeNumber: 'BB225',
    firstName: 'Cheska Nicole',
    middleName: 'Lico',
    lastName: 'Santiago',
    name: 'Cheska Nicole Santiago',
    email: 'cheskanicole.santiago@hdiadventures.com',
    username: 'cheskanicole.santiago',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_fa_adv',
    departmentName: 'Finance and Accounting',
    position: 'FINANCE ANALYST',
    immediateSuperiorId: 'usr_e1752',
    immediateSuperiorName: 'Emmanuel Buenaventura',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_bb223',
    employeeNumber: 'BB223',
    firstName: 'Michael Julius',
    middleName: 'Ramos',
    lastName: 'Vallejos',
    name: 'Michael Julius Vallejos',
    email: 'michaeljulius.vallejos@hdiadventures.com',
    username: 'michaeljulius.vallejos',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_legal_adv',
    departmentName: 'Peoples Ops Legal',
    position: 'Team Member-Regulatory and government compliance',
    immediateSuperiorId: 'usr_e1813',
    immediateSuperiorName: 'Jemimah Naomi De Los Santos',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1804',
    employeeNumber: 'E1804',
    firstName: 'Dianne Rose',
    middleName: 'Corpez',
    lastName: 'Dadula',
    name: 'Dianne Rose Dadula',
    email: 'diannerose.dadula@hdiadventures.com',
    username: 'diannerose.dadula',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_sales_adv',
    departmentName: 'Sales',
    position: 'Strategic Alliance Partnership',
    immediateSuperiorId: 'usr_e1752',
    immediateSuperiorName: 'Emmanuel Buenaventura',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1805',
    employeeNumber: 'E1805',
    firstName: 'Marco',
    middleName: 'Paramio',
    lastName: 'Bermudez',
    name: 'Marco Bermudez',
    email: 'marco.bermudez@hdiadventures.com',
    username: 'marco.bermudez',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_bmc_adv',
    departmentName: 'BMC',
    position: 'Support Member-Multimedia Design',
    immediateSuperiorId: 'usr_e1302',
    immediateSuperiorName: 'Anmer Carrillo',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1808',
    employeeNumber: 'E1808',
    firstName: 'Jasmine',
    middleName: 'Escobido',
    lastName: 'Barraca',
    name: 'Jasmine Barraca',
    email: 'jasmine.barraca@hdiadventures.com',
    username: 'jasmine.barraca',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_adm_adv',
    departmentName: 'Administration',
    position: 'Purchasing and Admin',
    immediateSuperiorId: 'usr_e1787',
    immediateSuperiorName: 'James Ivan Luigi Abendan',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1809',
    employeeNumber: 'E1809',
    firstName: 'John Vryan',
    middleName: 'Yangco',
    lastName: 'Ople',
    name: 'John Vryan Ople',
    email: 'johnvryan.ople@hdiadventures.com',
    username: 'johnvryan.ople',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_bmc_adv',
    departmentName: 'BMC',
    position: 'Project Leader-Multimedia Designer',
    immediateSuperiorId: 'usr_e1302',
    immediateSuperiorName: 'Anmer Carrillo',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1811',
    employeeNumber: 'E1811',
    firstName: 'Christine Joy',
    middleName: 'Gipanao',
    lastName: 'Fario',
    name: 'Christine Joy Fario',
    email: 'christinejoy.fario@hdiadventures.com',
    username: 'christinejoy.fario',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_bmc_adv',
    departmentName: 'BMC',
    position: 'Support Member-Marketing',
    immediateSuperiorId: 'usr_e1538',
    immediateSuperiorName: 'Pamela Maureen Fernando',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1812',
    employeeNumber: 'E1812',
    firstName: 'Mark Jazzam',
    middleName: 'Sarmiento',
    lastName: 'Marbello',
    name: 'Mark Jazzam Marbello',
    email: 'markjazzam.marbello@hdiadventures.com',
    username: 'markjazzam.marbello',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_ops_adv',
    departmentName: 'Operations',
    position: 'Project leader-Engineer',
    immediateSuperiorId: 'usr_e1115',
    immediateSuperiorName: 'Manuel, Jr. Embuido',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1115',
    employeeNumber: 'E1115',
    firstName: 'Manuel, Jr.',
    middleName: 'Castro',
    lastName: 'Embuido',
    name: 'Manuel Embuido Jr.',
    email: 'manuel.embuido@hdiadventures.com',
    username: 'manuel.embuido',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_ops_adv',
    departmentName: 'Operations',
    position: 'Team Leader-Operations',
    immediateSuperiorId: 'usr_e1752',
    immediateSuperiorName: 'Emmanuel Buenaventura',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1147',
    employeeNumber: 'E1147',
    firstName: 'Gracia',
    middleName: 'Azucena',
    lastName: 'Esguerra',
    name: 'Gracia Esguerra',
    email: 'gracia.esguerra@hdiadventures.com',
    username: 'gracia.esguerra',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_sales_adv',
    departmentName: 'Sales',
    position: 'Team Leader-Sales',
    immediateSuperiorId: 'usr_e1752',
    immediateSuperiorName: 'Emmanuel Buenaventura',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1078',
    employeeNumber: 'E1078',
    firstName: 'Ariel',
    middleName: 'Medel',
    lastName: 'Javier',
    name: 'Ariel Javier',
    email: 'ariel.javier@hdiadventures.com',
    username: 'ariel.javier',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_ops_adv',
    departmentName: 'Operations',
    position: 'Support Member-Driver',
    immediateSuperiorId: 'usr_e1115',
    immediateSuperiorName: 'Manuel, Jr. Embuido',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1254',
    employeeNumber: 'E1254',
    firstName: 'Robert',
    middleName: 'Cuevas',
    lastName: 'Lulab',
    name: 'Robert Lulab',
    email: 'robert.lulab@hdiadventures.com',
    username: 'robert.lulab',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_adm_adv',
    departmentName: 'Administration',
    position: 'Project Leader-Safety and Building maintenance',
    immediateSuperiorId: 'usr_e1787',
    immediateSuperiorName: 'James Ivan Luigi Abendan',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1215',
    employeeNumber: 'E1215',
    firstName: 'Jarry',
    middleName: 'Cortez',
    lastName: 'Samar',
    name: 'Jarry Samar',
    email: 'jarry.samar@hdiadventures.com',
    username: 'jarry.samar',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_adm_adv',
    departmentName: 'Administration',
    position: 'Support Member-Liaison',
    immediateSuperiorId: 'usr_e1254',
    immediateSuperiorName: 'Robert Lulab',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1537',
    employeeNumber: 'E1537',
    firstName: 'Mark Ryan',
    middleName: 'Lopez',
    lastName: 'Mariano',
    name: 'Mark Ryan Mariano',
    email: 'markryan.mariano@hdiadventures.com',
    username: 'markryan.mariano',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_ops_adv',
    departmentName: 'Operations',
    position: 'Team Member-Technician',
    immediateSuperiorId: 'usr_e1115',
    immediateSuperiorName: 'Manuel, Jr. Embuido',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1709',
    employeeNumber: 'E1709',
    firstName: 'Mcklein',
    middleName: 'Malatamban',
    lastName: 'Ordiz',
    name: 'Mcklein Ordiz',
    email: 'mcklein.ordiz@hdiadventures.com',
    username: 'mcklein.ordiz',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_adm_adv',
    departmentName: 'Administration',
    position: 'Team Member-Messenger',
    immediateSuperiorId: 'usr_e1254',
    immediateSuperiorName: 'Robert Lulab',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1787',
    employeeNumber: 'E1787',
    firstName: 'James Ivan Luigi',
    middleName: 'Ignacio',
    lastName: 'Abendan',
    name: 'James Ivan Luigi Abendan',
    email: 'james.abendan@hdiadventures.com',
    username: 'james.abendan',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_adm_adv',
    departmentName: 'Administration',
    position: 'Junior Project Leader-IT Technical',
    immediateSuperiorId: 'usr_e1752',
    immediateSuperiorName: 'Emmanuel Buenaventura',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1816',
    employeeNumber: 'E1816',
    firstName: 'Aillah Marie',
    middleName: 'Regilme',
    lastName: 'Ringor',
    name: 'Aillah Marie Ringor',
    email: 'aillahmarie.ringor@hdiadventures.com',
    username: 'aillahmarie.ringor',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_fa_adv',
    departmentName: 'Finance and Accounting',
    position: 'Team Member - Finance and Accounting',
    immediateSuperiorId: 'usr_e1806',
    immediateSuperiorName: 'Mary Anne Murphy',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1817',
    employeeNumber: 'E1817',
    firstName: 'Jinky',
    middleName: 'Araza',
    lastName: 'Pabunan',
    name: 'Jinky Pabunan',
    email: 'jinky.pabunan@hdiadventures.com',
    username: 'jinky.pabunan',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_fa_adv',
    departmentName: 'Finance and Accounting',
    position: 'Team Member - Finance and Accounting',
    immediateSuperiorId: 'usr_e1806',
    immediateSuperiorName: 'Mary Anne Murphy',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1556',
    employeeNumber: 'E1556',
    firstName: 'Joel',
    middleName: 'Dividina',
    lastName: 'Villanueva',
    name: 'Joel Villanueva',
    email: 'joel.villanueva@hdiadventures.com',
    username: 'joel.villanueva',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_legal_adv',
    departmentName: 'Peoples Ops Legal',
    position: 'Support Member-Warehouseman',
    immediateSuperiorId: 'usr_e1813',
    immediateSuperiorName: 'Jemimah Naomi De Los Santos',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1820',
    employeeNumber: 'E1820',
    firstName: 'Jose Raphael',
    middleName: 'Ganata',
    lastName: 'del Rosario',
    name: 'Jose Raphael del Rosario',
    email: 'joseraphael.delrosario@hdiadventures.com',
    username: 'joseraphael.delrosario',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_adm_adv',
    departmentName: 'Administration',
    position: 'Support Member - Admin',
    immediateSuperiorId: 'usr_e1787',
    immediateSuperiorName: 'James Ivan Luigi Abendan',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1824',
    employeeNumber: 'E1824',
    firstName: 'Christine Nicole',
    middleName: '',
    lastName: 'Villanueva',
    name: 'Christine Nicole Villanueva',
    email: 'christinenicole.villanueva@hdiadventures.com',
    username: 'christinenicole.villanueva',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_fa_adv',
    departmentName: 'Finance and Accounting',
    position: 'Team Member - Finance and Accounting',
    immediateSuperiorId: 'usr_e1714',
    immediateSuperiorName: 'Dana Miran',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1825',
    employeeNumber: 'E1825',
    firstName: 'Christian',
    middleName: 'Manozo',
    lastName: 'Sucgang',
    name: 'Christian Sucgang',
    email: 'christian.sucgang@hdiadventures.com',
    username: 'christian.sucgang',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_sales_adv',
    departmentName: 'Sales',
    position: 'Project Leader - Sales Creative Maverick',
    immediateSuperiorId: 'usr_e1752',
    immediateSuperiorName: 'Emmanuel Buenaventura',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_e1813',
    employeeNumber: 'E1813',
    firstName: 'Jemimah Naomi',
    middleName: 'Jandoc',
    lastName: 'De Los Santos',
    name: 'Jemimah Naomi De Los Santos',
    email: 'jemimahnaomi.delossantos@hdiadventures.com',
    username: 'jemimahnaomi.delossantos',
    password: 'password',
    role: 'supervisor',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_legal_adv',
    departmentName: 'Peoples Ops Legal',
    position: 'Team Leader-Legal',
    immediateSuperiorId: 'usr_ceo_brandon',
    immediateSuperiorName: 'Brandon Chia',
    employmentStatus: 'Regular',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_proj1',
    employeeNumber: 'Proj-1',
    firstName: 'Hanlene Charlize',
    middleName: 'Pio',
    lastName: 'Caberte',
    name: 'Hanlene Charlize Caberte',
    email: 'hanlenecharlize.caberte@hdiadventures.com',
    username: 'hanlenecharlize.caberte',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_bmc_adv',
    departmentName: 'BMC',
    position: 'Project-Based Marketing Assistant',
    immediateSuperiorId: 'usr_e1538',
    immediateSuperiorName: 'Pamela Maureen Fernando',
    employmentStatus: 'Project-based',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
  {
    id: 'usr_proj2',
    employeeNumber: 'Proj-2',
    firstName: 'Jhoy',
    middleName: 'Balbas',
    lastName: 'Paulino',
    name: 'Jhoy Paulino',
    email: 'jhoy.paulino@hdiadventures.com',
    username: 'jhoy.paulino',
    password: 'password',
    role: 'employee',
    companyId: 'comp_adventures',
    companyName: 'Adventures',
    departmentId: 'dept_adm_adv',
    departmentName: 'Administration',
    position: 'Project-Based Web Developer',
    immediateSuperiorId: 'usr_e1787',
    immediateSuperiorName: 'James Ivan Luigi Abendan',
    employmentStatus: 'Project-based',
    isActive: true,
    isApproved: true,
    approvalStatus: 'approved',
  },
];
